// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHec1-jsNFFAMWJfDmCYfzGRd7mVvm9U',
    appId: '1:912423152676:web:2753fdd72f9ce31d623cb1',
    messagingSenderId: '912423152676',
    projectId: 'coach-ab49b',
    authDomain: 'coach-ab49b.firebaseapp.com',
    storageBucket: 'coach-ab49b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGhKcwPMCcLf2LqZS0s2ZK7KeSSxUe18',
    appId: '1:912423152676:android:12e675feb499dba6623cb1',
    messagingSenderId: '912423152676',
    projectId: 'coach-ab49b',
    storageBucket: 'coach-ab49b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaXZg8grahn2Bes_nzMQXNWnkzB0-aM0Q',
    appId: '1:912423152676:ios:09fe3be39fe78085623cb1',
    messagingSenderId: '912423152676',
    projectId: 'coach-ab49b',
    storageBucket: 'coach-ab49b.appspot.com',
    iosClientId: '912423152676-21svn57vc4kekqoocb051ghlb2037f5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bussinesCoach',
  );
}
